@startuml
'https://plantuml.com/class-diagram

class Etudiant{
    - id : Identite
    - form : Formation
    - resultats : Hashmap<String,Set<Double>>
    + addNote(String mat,double note)
    + calcMoy(String mat) : double
    + calcMoyGen() : double
}

class Identite{
    - String NIP
    - String nom
    - String prenom
}

class Formation{
    - String identifiant
    - Hashmap<String,Integer> mat
    + addMat(String nom, int coeff)
    + supMat(String nom)
    + getCoeff(String mat) : int
}

class Groupe{
    - grp : Hashmap<Etudiant,Formation>
    + addEtu(Etudiant etu)
    + supEtu(Etudiant etu)
}

Groupe -up-> Etudiant
Groupe -down-> Formation
Etudiant -> Formation
Etudiant -> Identite


@enduml
